language: node_js
node_js:
  - "8"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
  directories:
    - $HOME/.npm
script:
  - npm test
  - npm run docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs/
  on:
    branch: master
