language: node_js
node_js:
  - "6"
  - "node"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
  directories:
    - $HOME/.npm
script:
  - npm test
env:
  - TRAVIS=travis CXX=g++-4.8
